const CompetenceNom = {
    Technique: 'Technique',
    Programmation: 'Programmation',
    Analyse_de_données: 'Analyse de données',
    Science_des_données: 'Science des données',
    Développement_web: 'Développement web',
    Développement_mobile: 'Développement mobile',
    Administration_de_réseau: 'Administration de réseau',
    Cyber_sécurité: 'Cyber sécurité',
    Ingénierie_matérielle: 'Ingénierie matérielle',
    Ingénierie_logicielle: 'Ingénierie logicielle',
    Assurance_qualité: 'Assurance qualité',
    Cloud_computing: 'Cloud computing',
    Interpersonnelle: 'Interpersonnelle',
    Communication: 'Communication',
    Leadership: 'Leadership',
    Management: 'Management',
    Créativité: 'Créativité',
    Analytique: 'Analytique',
    Organisationnelle: 'Organisationnelle',
    Stratégique: 'Stratégique',
    Administrative: 'Administrative',
    Recherche: 'Recherche',
    Vente: 'Vente',
    Marketing: 'Marketing',
    Financière: 'Financière',
    Planification: 'Planification',
    Résolution_de_problèmes: 'Résolution de problèmes',
    Esprit_équipe: 'Esprit d\'équipe',
    Gestion_du_temps: 'Gestion du temps',
    Coaching: 'Coaching',
    Prise_de_décision: 'Prise de décision',
    Négociation: 'Négociation',
    Gestion_de_projet: 'Gestion de projet',
    Service_client: 'Service client',
    Innovation: 'Innovation',
    Adaptabilité: 'Adaptabilité',
    Pensée_critique: 'Pensée critique',
    Résolution_de_conflits: 'Résolution de conflits',
    Multilingue: 'Multilingue',
    Conscience_interculturelle: 'Conscience interculturelle'
  };
  
  export default CompetenceNom;
  