export const countries = [
    {
      name: 'Afrique du Sud',
      cities: ['Johannesburg', 'Le Cap', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein'],
    },
    {
      name: 'Algérie',
      cities: ["Alger",
      "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Béchar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tébessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Sétif",
  "Saïda",
  "Skikda",
  "Sidi Bel Abbès",
  "Annaba",
  "Guelma",
  "Constantine",
  "Médéa",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arréridj",
  "Boumerdès",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Aïn Defla",
  "Naâma",
  "Aïn Témouchent",
  "Ghardaïa",
  "Relizane",
  "El M'ghair",
  "El Menia",
  "Ouled Djellal",
  "Bordj Baji Mokhtar",
  "Beni Abbes",
  "Timimoun",
  "Touggourt",
  "Djanet",
  "In Salah",
  "In Guezzam"],
    },
    {
      name: 'Allemagne',
      cities: ['Berlin', 'Hambourg', 'Munich', 'Cologne', 'Francfort', 'Stuttgart'],
    },
    {
      name: 'Angleterre',
      cities: ['Londres', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Newcastle'],
    },
    {
      name: 'Arabie Saoudite',
      cities: ['Riyad', 'Jeddah', 'Makkah', 'Madinah', 'Dammam', 'Taif'],
    },
    {
      name: 'Argentine',
      cities: ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza', 'Tucuman', 'La Plata'],
    },
    {
      name: 'Australie',
      cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast'],
    },
    {
      name: 'Autriche',
      cities: ['Vienne', 'Graz', 'Linz', 'Salzbourg', 'Innsbruck', 'Klagenfurt'],
    },
    {
      name: 'Belgique',
      cities: ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège', 'Bruges'],
    },
    {
      name: 'Bénin',
      cities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon', 'Kandi'],
    },
    {
      name: 'Brésil',
      cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte'],
    },
    {
      name: 'Canada',
      cities: ['Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Ottawa', 'Edmonton'],
    },
    {
      name: 'Chine',
      cities: ['Pékin', 'Shanghai', 'Canton', 'Shenzhen', 'Chongqing', 'Hangzhou'],
    },
    {
      name: 'Égypte',
      cities: ['Le Caire', 'Alexandrie', 'Gizeh', 'Port-Saïd', 'Suez', 'Luxor'],
    },
    {
      name: 'Espagne',
      cities: ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Bilbao', 'Malaga'],
    },
    {
      name: 'États-Unis',
      cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia'],
    },
    {
      name: 'France',
      cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes'],
    },
    {
      name: 'Inde',
      cities: ['New Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad'],
    },
    {
      name: 'Italie',
      cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence', 'Venise'],
    },
    {
      name: 'Japon',
      cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Kyoto'],
    },
    {
      name: 'Maroc',
      cities: ['Casablanca', 'Rabat', 'Fès', 'Marrakech', 'Tanger', 'Agadir'],
    },
    {
      name: 'Mexique',
      cities: ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León'],
    },
    {
      name: 'Nigeria',
      cities: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City'],
    },
    {
      name: 'Pays-Bas',
      cities: ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht', 'Eindhoven', 'Tilburg'],
    },
    {
      name: 'Russie',
      cities: ['Moscou', 'Saint-Pétersbourg', 'Novossibirsk', 'Ekaterinbourg', 'Kazan', 'Nijni Novgorod'],
    },
    
  
  ];
  